#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'iptables'
cookbook 'git'
cookbook 'knockd', :git => 'https://github.com/aldoborrero/chef-solo-search.git'
cookbook 'munin'
cookbook 'mysql'
cookbook 'openssh'
cookbook 'php'
cookbook 'solo-search', :git => 'https://github.com/aldoborrero/chef-solo-search.git'
cookbook 'sudo'
cookbook 'users'
cookbook 'varnish'
cookbook 'zsh'